name: Python Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  read-config:
    name: Read Config
    runs-on: windows-latest
    outputs:
      createTestData: ${{ steps.config.outputs.createTestData }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pyyaml
      - id: config
        shell: bash
        run: |
          CREATE_TEST_DATA=$(python -c "import yaml; print(str(yaml.safe_load(open('config.yaml'))['createTestData']).lower())")
          echo "createTestData=$CREATE_TEST_DATA" >> $GITHUB_OUTPUT
  
  

  test-data:
    name: Test Data Creation
    needs: read-config
    if: needs.read-config.outputs.createTestData == 'True'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python test_data_creator.py
      - name: Upload dummy_data.txt
        uses: actions/upload-artifact@v3
        with:
          name: dummy-data
          path: dummy_data.txt


  test:
    name: Run Tests
    needs: [ read-config, test-data ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Run Pytest Tests
        run: pytest tests/


  reconciliation:
    name: Reconciliation
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python reconciliation.py

  reporting:
    name: Generate Report
    needs: reconciliation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Report
        run: echo "Pipeline complete! Check Allure results from previous step."
